Update currency
fix when convert rate is less than 1

diff --git a/currency/currency b/currency/currency
--- a/currency/currency
+++ b/currency/currency
@@ -22,7 +22,7 @@ currencyCodes=(AUD BGN BRL CAD CHF CNY CZK DKK
     elif command -v fetch &>/dev/null; then
       configuredClient="fetch"
     else
-      echo "Error: This tool requires either curl, wget, httpie or fetch to be installed." >&2
+      echo "Error: This tool reqires either curl, wget, httpie or fetch to be installed." >&2
       return 1
     fi
   }
@@ -136,7 +136,7 @@ checkInternet()
 ## Grabs the exchange rate and does the math for converting the currency
 convertCurrency()
 {
-  exchangeRate=$(httpGet "https://api.exchangeratesapi.io/latest?base=$base" | grep -Eo "$exchangeTo\":[1-9.]*" | grep -Eo "[0-9.]*") > /dev/null
+  exchangeRate=$(httpGet "https://api.exchangeratesapi.io/latest?base=$base" | grep -Eo "$exchangeTo\":[0-9.]+" | grep -Eo "[0-9.]+") > /dev/null
   if ! command -v bc &>/dev/null; then
     oldRate=$exchangeRate
     exchangeRate=$(echo $exchangeRate | grep -Eo "^[0-9]*" )
